# Generated by Django 5.0.6 on 2024-05-24 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('author', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('imageUrl', models.URLField()),
                ('published_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
