# Generated by Django 5.0.6 on 2024-05-24 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_article_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='imageUrl',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='article',
            name='published_date',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='article',
            name='url',
            field=models.CharField(max_length=1000),
        ),
    ]
