# Generated by Django 5.0.6 on 2024-06-27 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_article_author_alter_article_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
