# Generated by Django 5.0.6 on 2024-07-06 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_article_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='country',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
